// fronted/src/components/Header.jsx
import React from 'react';
import ServerStatus from './ServerStatus'; // 确保路径正确
import Weather from './Weather'; // 确保路径正确
import './Header.css'; // 引入CSS文件

const AppHeader = () => {
    return (
        <header className="header">
            <img className="header_picture" src="/images/head_pic.jpg" alt="head_pic" />
            <ServerStatus />
            <Weather />
        </header>
    );
};

export default AppHeader;

// src/components/Header.vue
<template>
    <header class="header">
        <img class="header_picture" src="/images/head_pic.jpg" alt="head_pic" />
        <ServerStatus />
        <Weather />
    </header>
</template>

<script>
    import ServerStatus from "./ServerStatus.vue"; // 确保路径正确
    import Weather from "./Weather.vue"; // 确保路径正确

    export default {
    name: 'Header,
    components: {
    ServerStatus,
    Weather
}
};
</script>

<style scoped>
    @import './Header.css'; /* 引入 CSS 文件 */
</style>

export default Header;
